"""Executable, representation-matched classical controls for QAtelier."""

from .models import (
    ClassicalDependencyError,
    ClassicalModel,
    EvaluationResult,
    MODEL_NAMES,
    OptionalDependencyError,
    RepresentationMetadata,
    SpectrumSpec,
    assert_matched_representations,
    available_models,
    build_model,
    evaluate,
    evaluate_model,
    predict,
    train,
    train_finite_rbf,
    train_linear_svm,
    train_logistic,
    train_low_rank_bilinear,
    train_matched_mlp,
    train_mps,
    train_polynomial_svm,
    train_rbf_svm,
    train_rff,
    train_spectrum_matched,
)

__all__ = [
    "ClassicalDependencyError",
    "ClassicalModel",
    "EvaluationResult",
    "MODEL_NAMES",
    "OptionalDependencyError",
    "RepresentationMetadata",
    "SpectrumSpec",
    "assert_matched_representations",
    "available_models",
    "build_model",
    "evaluate",
    "evaluate_model",
    "predict",
    "train",
    "train_finite_rbf",
    "train_linear_svm",
    "train_logistic",
    "train_low_rank_bilinear",
    "train_matched_mlp",
    "train_mps",
    "train_polynomial_svm",
    "train_rbf_svm",
    "train_rff",
    "train_spectrum_matched",
]
